[project]
name = "rl-betaflight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elrs>=0.0.7",
    "pyvicon-datastream>=0.2.4",
]
